
local Instance = {}
Instance.Archivable = true
Instance.RobloxLocked = true
Instance.Sandboxed = true
Instance.archivable = true
local AccessoryDescription = {}
AccessoryDescription.IsLayered = true
AccessoryDescription.Puffiness = 0
local AccountService = {}
local Accoutrement = {}
local Accessory = {}
local Hat = {}
local ActivityHistoryService = {}
local AdPortal = {}
local AdService = {}
local AdvancedDragger = {}
local AnalyticsService = {}
local Animation = {}
local AnimationClip = {}
AnimationClip.Loop = true
local CurveAnimation = {}
local KeyframeSequence = {}
KeyframeSequence.AuthoredHipHeight = 0
local AnimationClipProvider = {}
local AnimationController = {}
local AnimationFromVideoCreatorService = {}
local AnimationFromVideoCreatorStudioService = {}
local AnimationRigData = {}
local AnimationStreamTrack = {}
AnimationStreamTrack.IsPlaying = true
AnimationStreamTrack.WeightCurrent = 0
AnimationStreamTrack.WeightTarget = 0
local AnimationTrack = {}
AnimationTrack.IsPlaying = true
AnimationTrack.Length = 0
AnimationTrack.Looped = true
AnimationTrack.Speed = 0
AnimationTrack.TimePosition = 0
AnimationTrack.WeightCurrent = 0
AnimationTrack.WeightTarget = 0
local Animator = {}
Animator.EvaluationThrottled = true
Animator.PreferLodEnabled = true
Animator.RootMotionWeight = 0
local AppUpdateService = {}
local AssetCounterService = {}
local AssetDeliveryProxy = {}
AssetDeliveryProxy.StartServer = true
local AssetImportService = {}
local AssetImportSession = {}
local AssetManagerService = {}
local AssetPatchSettings = {}
local AssetService = {}
local Atmosphere = {}
Atmosphere.Density = 0
Atmosphere.Glare = 0
Atmosphere.Haze = 0
Atmosphere.Offset = 0
local Attachment = {}
Attachment.Visible = true
local Bone = {}
local AudioAnalyzer = {}
AudioAnalyzer.PeakLevel = 0
AudioAnalyzer.RmsLevel = 0
local AudioChorus = {}
AudioChorus.Depth = 0
AudioChorus.Mix = 0
AudioChorus.Rate = 0
local AudioCompressor = {}
AudioCompressor.Attack = 0
AudioCompressor.MakeupGain = 0
AudioCompressor.Ratio = 0
AudioCompressor.Release = 0
AudioCompressor.Threshold = 0
local AudioDeviceInput = {}
AudioDeviceInput.Active = true
AudioDeviceInput.IsReady = true
AudioDeviceInput.Muted = true
local AudioDeviceOutput = {}
local AudioDistortion = {}
AudioDistortion.Level = 0
local AudioEcho = {}
AudioEcho.DelayTime = 0
AudioEcho.DryLevel = 0
AudioEcho.Feedback = 0
AudioEcho.WetLevel = 0
local AudioEmitter = {}
local AudioEqualizer = {}
AudioEqualizer.HighGain = 0
AudioEqualizer.LowGain = 0
AudioEqualizer.MidGain = 0
local AudioFader = {}
AudioFader.Volume = 0
local AudioFlanger = {}
AudioFlanger.Depth = 0
AudioFlanger.Mix = 0
AudioFlanger.Rate = 0
local AudioListener = {}
local AudioPitchShifter = {}
AudioPitchShifter.Pitch = 0
local AudioPlayer = {}
AudioPlayer.AutoLoad = true
AudioPlayer.IsPlaying = true
AudioPlayer.IsReady = true
AudioPlayer.Looping = true
local AudioReverb = {}
AudioReverb.DecayRatio = 0
AudioReverb.DecayTime = 0
AudioReverb.Density = 0
AudioReverb.Diffusion = 0
AudioReverb.DryLevel = 0
AudioReverb.EarlyDelayTime = 0
AudioReverb.HighCutFrequency = 0
AudioReverb.LateDelayTime = 0
AudioReverb.LowShelfFrequency = 0
AudioReverb.LowShelfGain = 0
AudioReverb.ReferenceFrequency = 0
AudioReverb.WetLevel = 0
local AudioSearchParams = {}
local AvatarChatService = {}
AvatarChatService.ClientFeaturesInitialized = true
local AvatarCreationService = {}
local AvatarEditorService = {}
local AvatarGenerationJob = {}
AvatarGenerationJob.Progress = 0
local Avatar2DGenerationJob = {}
local Avatar3DGenerationJob = {}
local AvatarGenerationSession = {}
local AvatarImportService = {}
local Backpack = {}
local BadgeService = {}
local BaseImportData = {}
BaseImportData.ShouldImport = true
local AnimationImportData = {}
local FacsImportData = {}
local GroupImportData = {}
GroupImportData.Anchored = true
GroupImportData.ImportAsModelAsset = true
GroupImportData.InsertInWorkspace = true
local JointImportData = {}
local MaterialImportData = {}
MaterialImportData.IsPbr = true
local MeshImportData = {}
MeshImportData.Anchored = true
MeshImportData.CageManifold = true
MeshImportData.CageMeshIntersectedPreview = true
MeshImportData.CageMeshNotIntersected = true
MeshImportData.CageNoOverlappingVertices = true
MeshImportData.CageNonManifoldPreview = true
MeshImportData.CageOverlappingVerticesPreview = true
MeshImportData.CageUVMatched = true
MeshImportData.CageUVMisMatchedPreview = true
MeshImportData.DoubleSided = true
MeshImportData.IgnoreVertexColors = true
MeshImportData.IrrelevantCageModifiedPreview = true
MeshImportData.MeshHoleDetectedPreview = true
MeshImportData.MeshNoHoleDetected = true
MeshImportData.NoIrrelevantCageModified = true
MeshImportData.NoOuterCageFarExtendedFromMesh = true
MeshImportData.OuterCageFarExtendedFromMeshPreview = true
MeshImportData.PolygonCount = 0
MeshImportData.UseImportedPivot = true
local RootImportData = {}
RootImportData.AddModelToInventory = true
RootImportData.Anchored = true
RootImportData.AnimationIdForRestPose = 0
RootImportData.ImportAsModelAsset = true
RootImportData.ImportAsPackage = true
RootImportData.InsertInWorkspace = true
RootImportData.InsertWithScenePosition = true
RootImportData.InvertNegativeFaces = true
RootImportData.MergeMeshes = true
RootImportData.PolygonCount = 0
RootImportData.RigVisualization = true
RootImportData.UseSceneOriginAsCFrame = true
RootImportData.UseSceneOriginAsPivot = true
RootImportData.UsesCages = true
RootImportData.ValidateUgcBody = true
local BasePlayerGui = {}
local CoreGui = {}
local PlayerGui = {}
local StarterGui = {}
StarterGui.ProcessUserInput = true
StarterGui.ResetPlayerGuiOnSpawn = true
StarterGui.ShowDevelopmentGui = true
local BaseRemoteEvent = {}
local RemoteEvent = {}
local UnreliableRemoteEvent = {}
local BaseWrap = {}
local WrapLayer = {}
WrapLayer.Enabled = true
WrapLayer.Puffiness = 0
WrapLayer.ShrinkFactor = 0
local WrapTarget = {}
WrapTarget.Stiffness = 0
local Beam = {}
Beam.Brightness = 0
Beam.CurveSize0 = 0
Beam.CurveSize1 = 0
Beam.Enabled = true
Beam.FaceCamera = true
Beam.LightEmission = 0
Beam.LightInfluence = 0
Beam.TextureLength = 0
Beam.TextureSpeed = 0
Beam.Width0 = 0
Beam.Width1 = 0
Beam.ZOffset = 0
local BindableEvent = {}
local BindableFunction = {}
local BodyMover = {}
local BodyAngularVelocity = {}
BodyAngularVelocity.P = 0
local BodyForce = {}
local BodyGyro = {}
BodyGyro.D = 0
BodyGyro.P = 0
local BodyPosition = {}
BodyPosition.D = 0
BodyPosition.P = 0
local BodyThrust = {}
local BodyVelocity = {}
BodyVelocity.P = 0
local RocketPropulsion = {}
RocketPropulsion.CartoonFactor = 0
RocketPropulsion.MaxSpeed = 0
RocketPropulsion.MaxThrust = 0
RocketPropulsion.TargetRadius = 0
RocketPropulsion.ThrustD = 0
RocketPropulsion.ThrustP = 0
RocketPropulsion.TurnD = 0
RocketPropulsion.TurnP = 0
local BodyPartDescription = {}
local Breakpoint = {}
Breakpoint.ContinueExecution = true
Breakpoint.Enabled = true
Breakpoint.RemoveOnHit = true
Breakpoint.Valid = true
Breakpoint.Verified = true
local BrowserService = {}
local BubbleChatMessageProperties = {}
BubbleChatMessageProperties.TailVisible = true
local BulkImportService = {}
local CacheableContentProvider = {}
local HSRDataContentProvider = {}
local MeshContentProvider = {}
local SolidModelContentProvider = {}
local CalloutService = {}
local Camera = {}
Camera.DiagonalFieldOfView = 0
Camera.FieldOfView = 0
Camera.HeadLocked = true
Camera.HeadScale = 0
Camera.MaxAxisFieldOfView = 0
Camera.NearPlaneZ = 0
Camera.VRTiltAndRollEnabled = true
local CaptureService = {}
local ChangeHistoryService = {}
local CharacterAppearance = {}
local BodyColors = {}
local CharacterMesh = {}
local Clothing = {}
local Pants = {}
local Shirt = {}
local ShirtGraphic = {}
local Skin = {}
local Chat = {}
Chat.BubbleChatEnabled = true
Chat.LoadDefaultChat = true
local ChatbotUIService = {}
local ClickDetector = {}
ClickDetector.MaxActivationDistance = 0
local DragDetector = {}
DragDetector.ApplyAtCenterOfMass = true
DragDetector.Enabled = true
DragDetector.MaxDragAngle = 0
DragDetector.MaxForce = 0
DragDetector.MaxTorque = 0
DragDetector.MinDragAngle = 0
DragDetector.Responsiveness = 0
DragDetector.RunLocally = true
DragDetector.TrackballRadialPullFactor = 0
DragDetector.TrackballRollFactor = 0
local Clouds = {}
Clouds.Cover = 0
Clouds.Density = 0
Clouds.Enabled = true
local ClusterPacketCache = {}
local Collaborator = {}
Collaborator.IsIdle = true
local CollaboratorsService = {}
local CollectionService = {}
local CommandInstance = {}
CommandInstance.AllowGUIAccessPoints = true
CommandInstance.Checked = true
CommandInstance.Enabled = true
local CommandService = {}
local CommerceService = {}
local Configuration = {}
local ConfigureServerService = {}
local ConnectivityService = {}
local Constraint = {}
Constraint.Active = true
Constraint.Enabled = true
Constraint.Visible = true
local AlignOrientation = {}
AlignOrientation.MaxAngularVelocity = 0
AlignOrientation.MaxTorque = 0
AlignOrientation.PrimaryAxisOnly = true
AlignOrientation.ReactionTorqueEnabled = true
AlignOrientation.Responsiveness = 0
AlignOrientation.RigidityEnabled = true
local AlignPosition = {}
AlignPosition.ApplyAtCenterOfMass = true
AlignPosition.MaxForce = 0
AlignPosition.MaxVelocity = 0
AlignPosition.ReactionForceEnabled = true
AlignPosition.Responsiveness = 0
AlignPosition.RigidityEnabled = true
local AngularVelocity = {}
AngularVelocity.MaxTorque = 0
AngularVelocity.ReactionTorqueEnabled = true
local AnimationConstraint = {}
AnimationConstraint.IsKinematic = true
AnimationConstraint.MaxForce = 0
AnimationConstraint.MaxTorque = 0
local BallSocketConstraint = {}
BallSocketConstraint.LimitsEnabled = true
BallSocketConstraint.MaxFrictionTorque = 0
BallSocketConstraint.Radius = 0
BallSocketConstraint.Restitution = 0
BallSocketConstraint.TwistLimitsEnabled = true
BallSocketConstraint.TwistLowerAngle = 0
BallSocketConstraint.TwistUpperAngle = 0
BallSocketConstraint.UpperAngle = 0
local HingeConstraint = {}
HingeConstraint.AngularResponsiveness = 0
HingeConstraint.AngularSpeed = 0
HingeConstraint.AngularVelocity = 0
HingeConstraint.CurrentAngle = 0
HingeConstraint.LimitsEnabled = true
HingeConstraint.LowerAngle = 0
HingeConstraint.MotorMaxAcceleration = 0
HingeConstraint.MotorMaxTorque = 0
HingeConstraint.Radius = 0
HingeConstraint.Restitution = 0
HingeConstraint.ServoMaxTorque = 0
HingeConstraint.SoftlockServoUponReachingTarget = true
HingeConstraint.TargetAngle = 0
HingeConstraint.UpperAngle = 0
local LineForce = {}
LineForce.ApplyAtCenterOfMass = true
LineForce.InverseSquareLaw = true
LineForce.Magnitude = 0
LineForce.MaxForce = 0
LineForce.ReactionForceEnabled = true
local LinearVelocity = {}
LinearVelocity.ForceLimitsEnabled = true
LinearVelocity.LineVelocity = 0
LinearVelocity.MaxForce = 0
local PlaneConstraint = {}
local Plane = {}
local RigidConstraint = {}
local RodConstraint = {}
RodConstraint.CurrentDistance = 0
RodConstraint.Length = 0
RodConstraint.LimitAngle0 = 0
RodConstraint.LimitAngle1 = 0
RodConstraint.LimitsEnabled = true
RodConstraint.Thickness = 0
local RopeConstraint = {}
RopeConstraint.CurrentDistance = 0
RopeConstraint.Length = 0
RopeConstraint.Restitution = 0
RopeConstraint.Thickness = 0
RopeConstraint.WinchEnabled = true
RopeConstraint.WinchForce = 0
RopeConstraint.WinchResponsiveness = 0
RopeConstraint.WinchSpeed = 0
RopeConstraint.WinchTarget = 0
local SlidingBallConstraint = {}
SlidingBallConstraint.CurrentPosition = 0
SlidingBallConstraint.LimitsEnabled = true
SlidingBallConstraint.LinearResponsiveness = 0
SlidingBallConstraint.LowerLimit = 0
SlidingBallConstraint.MotorMaxAcceleration = 0
SlidingBallConstraint.MotorMaxForce = 0
SlidingBallConstraint.Restitution = 0
SlidingBallConstraint.ServoMaxForce = 0
SlidingBallConstraint.Size = 0
SlidingBallConstraint.SoftlockServoUponReachingTarget = true
SlidingBallConstraint.Speed = 0
SlidingBallConstraint.TargetPosition = 0
SlidingBallConstraint.UpperLimit = 0
SlidingBallConstraint.Velocity = 0
local CylindricalConstraint = {}
CylindricalConstraint.AngularLimitsEnabled = true
CylindricalConstraint.AngularResponsiveness = 0
CylindricalConstraint.AngularRestitution = 0
CylindricalConstraint.AngularSpeed = 0
CylindricalConstraint.AngularVelocity = 0
CylindricalConstraint.CurrentAngle = 0
CylindricalConstraint.InclinationAngle = 0
CylindricalConstraint.LowerAngle = 0
CylindricalConstraint.MotorMaxAngularAcceleration = 0
CylindricalConstraint.MotorMaxTorque = 0
CylindricalConstraint.RotationAxisVisible = true
CylindricalConstraint.ServoMaxTorque = 0
CylindricalConstraint.SoftlockAngularServoUponReachingTarget = true
CylindricalConstraint.TargetAngle = 0
CylindricalConstraint.UpperAngle = 0
local PrismaticConstraint = {}
local SpringConstraint = {}
SpringConstraint.Coils = 0
SpringConstraint.CurrentLength = 0
SpringConstraint.Damping = 0
SpringConstraint.FreeLength = 0
SpringConstraint.LimitsEnabled = true
SpringConstraint.MaxForce = 0
SpringConstraint.MaxLength = 0
SpringConstraint.MinLength = 0
SpringConstraint.Radius = 0
SpringConstraint.Stiffness = 0
SpringConstraint.Thickness = 0
local Torque = {}
local TorsionSpringConstraint = {}
TorsionSpringConstraint.Coils = 0
TorsionSpringConstraint.CurrentAngle = 0
TorsionSpringConstraint.Damping = 0
TorsionSpringConstraint.LimitEnabled = true
TorsionSpringConstraint.LimitsEnabled = true
TorsionSpringConstraint.MaxAngle = 0
TorsionSpringConstraint.MaxTorque = 0
TorsionSpringConstraint.Radius = 0
TorsionSpringConstraint.Restitution = 0
TorsionSpringConstraint.Stiffness = 0
local UniversalConstraint = {}
UniversalConstraint.LimitsEnabled = true
UniversalConstraint.MaxAngle = 0
UniversalConstraint.Radius = 0
UniversalConstraint.Restitution = 0
local VectorForce = {}
VectorForce.ApplyAtCenterOfMass = true
local ContentProvider = {}
local ContextActionService = {}
local Controller = {}
local HumanoidController = {}
local SkateboardController = {}
SkateboardController.Steer = 0
SkateboardController.Throttle = 0
local VehicleController = {}
local ControllerBase = {}
ControllerBase.Active = true
ControllerBase.BalanceRigidityEnabled = true
ControllerBase.MoveSpeedFactor = 0
local AirController = {}
AirController.BalanceMaxTorque = 0
AirController.BalanceSpeed = 0
AirController.MaintainAngularMomentum = true
AirController.MaintainLinearMomentum = true
AirController.MoveMaxForce = 0
AirController.TurnMaxTorque = 0
AirController.TurnSpeedFactor = 0
local ClimbController = {}
ClimbController.AccelerationTime = 0
ClimbController.BalanceMaxTorque = 0
ClimbController.BalanceSpeed = 0
ClimbController.MoveMaxForce = 0
local GroundController = {}
GroundController.AccelerationLean = 0
GroundController.AccelerationTime = 0
GroundController.BalanceMaxTorque = 0
GroundController.BalanceSpeed = 0
GroundController.DecelerationTime = 0
GroundController.Friction = 0
GroundController.FrictionWeight = 0
GroundController.GroundOffset = 0
GroundController.StandForce = 0
GroundController.StandSpeed = 0
GroundController.TurnSpeedFactor = 0
local SwimController = {}
SwimController.AccelerationTime = 0
SwimController.PitchMaxTorque = 0
SwimController.PitchSpeedFactor = 0
SwimController.RollMaxTorque = 0
SwimController.RollSpeedFactor = 0
local ControllerManager = {}
ControllerManager.BaseMoveSpeed = 0
ControllerManager.BaseTurnSpeed = 0
local ControllerService = {}
local ConversationalAIAcceptanceService = {}
local CookiesService = {}
local CorePackages = {}
local CoreScriptDebuggingManagerHelper = {}
local CoreScriptSyncService = {}
local CreationDBService = {}
local CrossDMScriptChangeListener = {}
local CustomEvent = {}
local CustomEventReceiver = {}
local DataModelMesh = {}
local BevelMesh = {}
local BlockMesh = {}
local CylinderMesh = {}
local EditableMesh = {}
local RobloxEditableMesh = {}
local FileMesh = {}
local SpecialMesh = {}
local DataModelPatchService = {}
local DataModelSession = {}
local DataStoreGetOptions = {}
DataStoreGetOptions.UseCache = true
local DataStoreIncrementOptions = {}
local DataStoreInfo = {}
local DataStoreKey = {}
local DataStoreKeyInfo = {}
local DataStoreObjectVersionInfo = {}
DataStoreObjectVersionInfo.IsDeleted = true
local DataStoreOptions = {}
DataStoreOptions.AllScopes = true
local DataStoreService = {}
DataStoreService.AutomaticRetry = true
DataStoreService.LegacyNamingScheme = true
local DataStoreSetOptions = {}
local Debris = {}
local DebugSettings = {}
DebugSettings.IsScriptStackTracingEnabled = true
DebugSettings.ReportSoundWarnings = true
local DebuggablePluginWatcher = {}
local DebuggerBreakpoint = {}
DebuggerBreakpoint.ContinueExecution = true
DebuggerBreakpoint.IsEnabled = true
DebuggerBreakpoint.isContextDependentBreakpoint = true
local DebuggerConnection = {}
DebuggerConnection.HasError = true
DebuggerConnection.IsPaused = true
local LocalDebuggerConnection = {}
local DebuggerConnectionManager = {}
local DebuggerLuaResponse = {}
DebuggerLuaResponse.IsError = true
DebuggerLuaResponse.IsSuccess = true
local DebuggerManager = {}
DebuggerManager.DebuggingEnabled = true
local DebuggerUIService = {}
local DebuggerVariable = {}
DebuggerVariable.Populated = true
local DebuggerWatch = {}
local DeviceIdService = {}
local Dialog = {}
Dialog.ConversationDistance = 0
Dialog.GoodbyeChoiceActive = true
Dialog.InUse = true
Dialog.TriggerDistance = 0
local DialogChoice = {}
DialogChoice.GoodbyeChoiceActive = true
local DraftsService = {}
local Dragger = {}
local DraggerService = {}
DraggerService.AlignDraggedObjects = true
DraggerService.AngleSnapEnabled = true
DraggerService.AngleSnapIncrement = 0
DraggerService.AnimateHover = true
DraggerService.CollisionsEnabled = true
DraggerService.HoverAnimateFrequency = 0
DraggerService.HoverThickness = 0
DraggerService.JointsEnabled = true
DraggerService.LinearSnapEnabled = true
DraggerService.LinearSnapIncrement = 0
DraggerService.PivotSnapToGeometry = true
DraggerService.ShowHover = true
DraggerService.ShowPivotIndicator = true
local EditableImage = {}
local RobloxEditableImage = {}
local EngineAPICloudProcessingService = {}
local EulerRotationCurve = {}
local EventIngestService = {}
local ExampleService = {}
local ExperienceAuthService = {}
local ExperienceInviteOptions = {}
local ExperienceNotificationService = {}
local ExperienceService = {}
local ExperienceStateCaptureService = {}
ExperienceStateCaptureService.IsInCaptureMode = true
local Explosion = {}
Explosion.BlastPressure = 0
Explosion.BlastRadius = 0
Explosion.DestroyJointRadiusPercent = 0
Explosion.TimeScale = 0
Explosion.Visible = true
local FaceAnimatorService = {}
FaceAnimatorService.AudioAnimationEnabled = true
FaceAnimatorService.FlipHeadOrientation = true
FaceAnimatorService.VideoAnimationEnabled = true
local FaceControls = {}
FaceControls.ChinRaiser = 0
FaceControls.ChinRaiserUpperLip = 0
FaceControls.Corrugator = 0
FaceControls.EyesLookDown = 0
FaceControls.EyesLookLeft = 0
FaceControls.EyesLookRight = 0
FaceControls.EyesLookUp = 0
FaceControls.FlatPucker = 0
FaceControls.Funneler = 0
FaceControls.JawDrop = 0
FaceControls.JawLeft = 0
FaceControls.JawRight = 0
FaceControls.LeftBrowLowerer = 0
FaceControls.LeftCheekPuff = 0
FaceControls.LeftCheekRaiser = 0
FaceControls.LeftDimpler = 0
FaceControls.LeftEyeClosed = 0
FaceControls.LeftEyeUpperLidRaiser = 0
FaceControls.LeftInnerBrowRaiser = 0
FaceControls.LeftLipCornerDown = 0
FaceControls.LeftLipCornerPuller = 0
FaceControls.LeftLipStretcher = 0
FaceControls.LeftLowerLipDepressor = 0
FaceControls.LeftNoseWrinkler = 0
FaceControls.LeftOuterBrowRaiser = 0
FaceControls.LeftUpperLipRaiser = 0
FaceControls.LipPresser = 0
FaceControls.LipsTogether = 0
FaceControls.LowerLipSuck = 0
FaceControls.MouthLeft = 0
FaceControls.MouthRight = 0
FaceControls.Pucker = 0
FaceControls.RightBrowLowerer = 0
FaceControls.RightCheekPuff = 0
FaceControls.RightCheekRaiser = 0
FaceControls.RightDimpler = 0
FaceControls.RightEyeClosed = 0
FaceControls.RightEyeUpperLidRaiser = 0
FaceControls.RightInnerBrowRaiser = 0
FaceControls.RightLipCornerDown = 0
FaceControls.RightLipCornerPuller = 0
FaceControls.RightLipStretcher = 0
FaceControls.RightLowerLipDepressor = 0
FaceControls.RightNoseWrinkler = 0
FaceControls.RightOuterBrowRaiser = 0
FaceControls.RightUpperLipRaiser = 0
FaceControls.TongueDown = 0
FaceControls.TongueOut = 0
FaceControls.TongueUp = 0
FaceControls.UpperLipSuck = 0
local FaceInstance = {}
local Decal = {}
Decal.LocalTransparencyModifier = 0
Decal.Shiny = 0
Decal.Specular = 0
Decal.Transparency = 0
local Texture = {}
Texture.OffsetStudsU = 0
Texture.OffsetStudsV = 0
Texture.StudsPerTileU = 0
Texture.StudsPerTileV = 0
local FacialAnimationRecordingService = {}
FacialAnimationRecordingService.BiometricDataConsent = true
local FacialAnimationStreamingServiceStats = {}
local FacialAnimationStreamingServiceV2 = {}
local FacialAnimationStreamingSubsessionStats = {}
local Feature = {}
local Hole = {}
local MotorFeature = {}
local File = {}
local Fire = {}
Fire.Enabled = true
Fire.Heat = 0
Fire.Size = 0
Fire.TimeScale = 0
Fire.size = 0
local FlagStandService = {}
local FloatCurve = {}
local FlyweightService = {}
local CSGDictionaryService = {}
local NonReplicatedCSGDictionaryService = {}
local Folder = {}
local ForceField = {}
ForceField.Visible = true
local FriendService = {}
local FunctionalTest = {}
local GamePassService = {}
local GameSettings = {}
GameSettings.VideoCaptureEnabled = true
GameSettings.VideoRecording = true
local GamepadService = {}
GamepadService.GamepadCursorEnabled = true
local Geometry = {}
local GeometryService = {}
local GetTextBoundsParams = {}
GetTextBoundsParams.Size = 0
GetTextBoundsParams.Width = 0
local GlobalDataStore = {}
local DataStore = {}
local OrderedDataStore = {}
local GoogleAnalyticsConfiguration = {}
local GroupService = {}
local GuiBase = {}
local GuiBase2d = {}
GuiBase2d.AbsoluteRotation = 0
GuiBase2d.AutoLocalize = true
GuiBase2d.IsNotOccluded = true
GuiBase2d.Localize = true
GuiBase2d.SelectionGroup = true
GuiBase2d.TotalGroupScale = 0
local GuiObject = {}
GuiObject.Active = true
GuiObject.BackgroundTransparency = 0
GuiObject.ClipsDescendants = true
GuiObject.Draggable = true
GuiObject.Interactable = true
GuiObject.Rotation = 0
GuiObject.Selectable = true
GuiObject.Transparency = 0
GuiObject.Visible = true
local CanvasGroup = {}
CanvasGroup.GroupTransparency = 0
local Frame = {}
local GuiButton = {}
GuiButton.AutoButtonColor = true
GuiButton.Modal = true
GuiButton.Selected = true
local ImageButton = {}
ImageButton.ImageTransparency = 0
ImageButton.IsLoaded = true
ImageButton.SliceScale = 0
local TextButton = {}
TextButton.LineHeight = 0
TextButton.RichText = true
TextButton.TextFits = true
TextButton.TextScaled = true
TextButton.TextSize = 0
TextButton.TextStrokeTransparency = 0
TextButton.TextTransparency = 0
TextButton.TextWrap = true
TextButton.TextWrapped = true
local GuiLabel = {}
local ImageLabel = {}
ImageLabel.ImageTransparency = 0
ImageLabel.IsLoaded = true
ImageLabel.SliceScale = 0
local TextLabel = {}
TextLabel.LineHeight = 0
TextLabel.RichText = true
TextLabel.TextFits = true
TextLabel.TextScaled = true
TextLabel.TextSize = 0
TextLabel.TextStrokeTransparency = 0
TextLabel.TextTransparency = 0
TextLabel.TextWrap = true
TextLabel.TextWrapped = true
local ScrollingFrame = {}
ScrollingFrame.ScrollBarImageTransparency = 0
ScrollingFrame.ScrollingEnabled = true
local TextBox = {}
TextBox.ClearTextOnFocus = true
TextBox.LineHeight = 0
TextBox.ManualFocusRelease = true
TextBox.MultiLine = true
TextBox.OverlayNativeInput = true
TextBox.RichText = true
TextBox.ShowNativeInput = true
TextBox.TextEditable = true
TextBox.TextFits = true
TextBox.TextScaled = true
TextBox.TextSize = 0
TextBox.TextStrokeTransparency = 0
TextBox.TextTransparency = 0
TextBox.TextWrap = true
TextBox.TextWrapped = true
local VideoFrame = {}
VideoFrame.IsLoaded = true
VideoFrame.Looped = true
VideoFrame.Playing = true
VideoFrame.Volume = 0
local ViewportFrame = {}
ViewportFrame.ImageTransparency = 0
ViewportFrame.IsMirrored = true
local LayerCollector = {}
LayerCollector.Enabled = true
LayerCollector.ResetOnSpawn = true
local BillboardGui = {}
BillboardGui.Active = true
BillboardGui.AlwaysOnTop = true
BillboardGui.Brightness = 0
BillboardGui.ClipsDescendants = true
BillboardGui.CurrentDistance = 0
BillboardGui.DistanceLowerLimit = 0
BillboardGui.DistanceStep = 0
BillboardGui.DistanceUpperLimit = 0
BillboardGui.LightInfluence = 0
BillboardGui.MaxDistance = 0
local PluginGui = {}
local DockWidgetPluginGui = {}
DockWidgetPluginGui.HostWidgetWasRestored = true
local QWidgetPluginGui = {}
local ScreenGui = {}
ScreenGui.ClipToDeviceSafeArea = true
ScreenGui.IgnoreGuiInset = true
ScreenGui.OnTopOfCoreBlur = true
local GuiMain = {}
local SurfaceGuiBase = {}
SurfaceGuiBase.Active = true
local AdGui = {}
AdGui.EnableVideoAds = true
local SurfaceGui = {}
SurfaceGui.AlwaysOnTop = true
SurfaceGui.Brightness = 0
SurfaceGui.ClipsDescendants = true
SurfaceGui.HorizontalCurvature = 0
SurfaceGui.LightInfluence = 0
SurfaceGui.MaxDistance = 0
SurfaceGui.PixelsPerStud = 0
SurfaceGui.ToolPunchThroughDistance = 0
SurfaceGui.ZOffset = 0
local GuiBase3d = {}
GuiBase3d.Transparency = 0
GuiBase3d.Visible = true
local FloorWire = {}
FloorWire.CycleOffset = 0
FloorWire.StudsBetweenTextures = 0
FloorWire.Velocity = 0
FloorWire.WireRadius = 0
local InstanceAdornment = {}
local SelectionBox = {}
SelectionBox.LineThickness = 0
SelectionBox.StudioSelectionBox = true
SelectionBox.SurfaceTransparency = 0
local PVAdornment = {}
local HandleAdornment = {}
HandleAdornment.AlwaysOnTop = true
local BoxHandleAdornment = {}
local ConeHandleAdornment = {}
ConeHandleAdornment.Height = 0
ConeHandleAdornment.Radius = 0
local CylinderHandleAdornment = {}
CylinderHandleAdornment.Angle = 0
CylinderHandleAdornment.Height = 0
CylinderHandleAdornment.InnerRadius = 0
CylinderHandleAdornment.Radius = 0
local ImageHandleAdornment = {}
local LineHandleAdornment = {}
LineHandleAdornment.Length = 0
LineHandleAdornment.Thickness = 0
local SphereHandleAdornment = {}
SphereHandleAdornment.Radius = 0
local WireframeHandleAdornment = {}
local ParabolaAdornment = {}
ParabolaAdornment.A = 0
ParabolaAdornment.B = 0
ParabolaAdornment.C = 0
ParabolaAdornment.Range = 0
ParabolaAdornment.Thickness = 0
local SelectionSphere = {}
SelectionSphere.SurfaceTransparency = 0
local PartAdornment = {}
local HandlesBase = {}
local ArcHandles = {}
local Handles = {}
local SurfaceSelection = {}
local SelectionLasso = {}
local SelectionPartLasso = {}
local SelectionPointLasso = {}
local Path2D = {}
Path2D.Thickness = 0
Path2D.Transparency = 0
Path2D.Visible = true
local GuiService = {}
GuiService.AutoSelectGuiEnabled = true
GuiService.CoreGuiNavigationEnabled = true
GuiService.GuiNavigationEnabled = true
GuiService.IsModalDialog = true
GuiService.IsWindows = true
GuiService.MenuIsOpen = true
GuiService.PreferredTransparency = 0
GuiService.ReducedMotionEnabled = true
GuiService.TouchControlsEnabled = true
local GuidRegistryService = {}
local HapticService = {}
local HeightmapImporterService = {}
local HiddenSurfaceRemovalAsset = {}
local Highlight = {}
Highlight.Enabled = true
Highlight.FillTransparency = 0
Highlight.OutlineTransparency = 0
local Hopper = {}
local HttpRbxApiService = {}
local HttpRequest = {}
local HttpService = {}
HttpService.HttpEnabled = true
local Humanoid = {}
Humanoid.AutoJumpEnabled = true
Humanoid.AutoRotate = true
Humanoid.AutomaticScalingEnabled = true
Humanoid.BreakJointsOnDeath = true
Humanoid.EvaluateStateMachine = true
Humanoid.Health = 0
Humanoid.HealthDisplayDistance = 0
Humanoid.HipHeight = 0
Humanoid.Jump = true
Humanoid.JumpHeight = 0
Humanoid.JumpPower = 0
Humanoid.MaxHealth = 0
Humanoid.MaxSlopeAngle = 0
Humanoid.NameDisplayDistance = 0
Humanoid.PlatformStand = true
Humanoid.RequiresNeck = true
Humanoid.Sit = true
Humanoid.UseJumpPower = true
Humanoid.WalkSpeed = 0
Humanoid.maxHealth = 0
local HumanoidDescription = {}
HumanoidDescription.BodyTypeScale = 0
HumanoidDescription.DepthScale = 0
HumanoidDescription.HeadScale = 0
HumanoidDescription.HeightScale = 0
HumanoidDescription.ProportionScale = 0
HumanoidDescription.WidthScale = 0
local IKControl = {}
IKControl.Enabled = true
IKControl.SmoothTime = 0
IKControl.Weight = 0
local ILegacyStudioBridge = {}
local LegacyStudioBridge = {}
local IXPService = {}
local IncrementalPatchBuilder = {}
IncrementalPatchBuilder.AddPathsToBundle = true
IncrementalPatchBuilder.HighCompression = true
IncrementalPatchBuilder.SerializePatch = true
IncrementalPatchBuilder.ZstdCompression = true
local InputObject = {}
local InsertService = {}
InsertService.AllowClientInsertModels = true
InsertService.AllowInsertFreeModels = true
local JointInstance = {}
JointInstance.Active = true
JointInstance.Enabled = true
local DynamicRotate = {}
DynamicRotate.BaseAngle = 0
local RotateP = {}
local RotateV = {}
local Glue = {}
local ManualSurfaceJointInstance = {}
local ManualGlue = {}
local ManualWeld = {}
local Motor = {}
Motor.CurrentAngle = 0
Motor.DesiredAngle = 0
Motor.MaxVelocity = 0
local Motor6D = {}
local Rotate = {}
local Snap = {}
local VelocityMotor = {}
VelocityMotor.CurrentAngle = 0
VelocityMotor.DesiredAngle = 0
VelocityMotor.MaxVelocity = 0
local Weld = {}
local JointsService = {}
local KeyboardService = {}
local Keyframe = {}
Keyframe.Time = 0
local KeyframeMarker = {}
local KeyframeSequenceProvider = {}
local LSPFileSyncService = {}
local LanguageService = {}
local Light = {}
Light.Brightness = 0
Light.Enabled = true
Light.Shadows = true
local PointLight = {}
PointLight.Range = 0
local SpotLight = {}
SpotLight.Angle = 0
SpotLight.Range = 0
local SurfaceLight = {}
SurfaceLight.Angle = 0
SurfaceLight.Range = 0
local Lighting = {}
Lighting.Brightness = 0
Lighting.ClockTime = 0
Lighting.EnvironmentDiffuseScale = 0
Lighting.EnvironmentSpecularScale = 0
Lighting.ExposureCompensation = 0
Lighting.FogEnd = 0
Lighting.FogStart = 0
Lighting.GeographicLatitude = 0
Lighting.GlobalShadows = true
Lighting.Outlines = true
Lighting.ShadowSoftness = 0
Lighting.TempUseNewSkyRemovalBehaviour = true
local LiveScriptingService = {}
local LocalStorageService = {}
local AppStorageService = {}
local UserStorageService = {}
local LocalizationService = {}
LocalizationService.IsTextScraperRunning = true
local LocalizationTable = {}
local CloudLocalizationTable = {}
local LodDataEntity = {}
LodDataEntity.EntityLodEnabled = true
local LodDataService = {}
local LogReporterService = {}
local LogService = {}
local LoginService = {}
local LuaSettings = {}
local LuaSourceContainer = {}
local BaseScript = {}
BaseScript.Disabled = true
BaseScript.Enabled = true
local CoreScript = {}
local Script = {}
local LocalScript = {}
local ModuleScript = {}
local LuaWebService = {}
local LuauScriptAnalyzerService = {}
local MarkerCurve = {}
local MarketplaceService = {}
local MaterialGenerationService = {}
local MaterialGenerationSession = {}
local MaterialService = {}
MaterialService.Use2022Materials = true
local MaterialVariant = {}
MaterialVariant.StudsPerTile = 0
local MemStorageConnection = {}
local MemStorageService = {}
local MemoryStoreHashMap = {}
local MemoryStoreQueue = {}
local MemoryStoreService = {}
local MemoryStoreSortedMap = {}
local Message = {}
local Hint = {}
local MessageBusConnection = {}
local MessageBusService = {}
local MessagingService = {}
local MetaBreakpoint = {}
MetaBreakpoint.ContinueExecution = true
MetaBreakpoint.Enabled = true
MetaBreakpoint.IsLogpoint = true
MetaBreakpoint.RemoveOnHit = true
MetaBreakpoint.Valid = true
local MetaBreakpointContext = {}
local MetaBreakpointManager = {}
local Mouse = {}
local PlayerMouse = {}
local PluginMouse = {}
local MouseService = {}
local MultipleDocumentInterfaceInstance = {}
local NetworkMarker = {}
local NetworkPeer = {}
local NetworkClient = {}
local NetworkServer = {}
local NetworkReplicator = {}
local ClientReplicator = {}
local ServerReplicator = {}
local NetworkSettings = {}
NetworkSettings.FreeMemoryMBytes = 0
NetworkSettings.HttpProxyEnabled = true
NetworkSettings.PrintJoinSizeBreakdown = true
NetworkSettings.PrintPhysicsErrors = true
NetworkSettings.PrintStreamInstanceQuota = true
NetworkSettings.RandomizeJoinInstanceOrder = true
NetworkSettings.RenderStreamedRegions = true
NetworkSettings.ShowActiveAnimationAsset = true
local NoCollisionConstraint = {}
NoCollisionConstraint.Enabled = true
local Noise = {}
local NotificationService = {}
NotificationService.IsConnected = true
NotificationService.IsLuaChatEnabled = true
NotificationService.IsLuaGameDetailsEnabled = true
local OmniRecommendationsService = {}
local OpenCloudApiV1 = {}
local OpenCloudService = {}
local OperationGraph = {}
local PVInstance = {}
local BasePart = {}
BasePart.Anchored = true
BasePart.AssemblyMass = 0
BasePart.BackParamA = 0
BasePart.BackParamB = 0
BasePart.BottomParamA = 0
BasePart.BottomParamB = 0
BasePart.CanCollide = true
BasePart.CanQuery = true
BasePart.CanTouch = true
BasePart.CastShadow = true
BasePart.Elasticity = 0
BasePart.EnableFluidForces = true
BasePart.Friction = 0
BasePart.FrontParamA = 0
BasePart.FrontParamB = 0
BasePart.LeftParamA = 0
BasePart.LeftParamB = 0
BasePart.LocalTransparencyModifier = 0
BasePart.Locked = true
BasePart.Mass = 0
BasePart.Massless = true
BasePart.ReceiveAge = 0
BasePart.Reflectance = 0
BasePart.RightParamA = 0
BasePart.RightParamB = 0
BasePart.SpecificGravity = 0
BasePart.TopParamA = 0
BasePart.TopParamB = 0
BasePart.Transparency = 0
local CornerWedgePart = {}
local FormFactorPart = {}
local Part = {}
local FlagStand = {}
local Platform = {}
local Seat = {}
Seat.Disabled = true
local SkateboardPlatform = {}
SkateboardPlatform.StickyWheels = true
local SpawnLocation = {}
SpawnLocation.AllowTeamChangeOnTouch = true
SpawnLocation.Enabled = true
SpawnLocation.Neutral = true
local WedgePart = {}
local Terrain = {}
Terrain.Decoration = true
Terrain.GrassLength = 0
Terrain.IsSmooth = true
Terrain.ShorelinesUpgraded = true
Terrain.SmoothVoxelsUpgraded = true
Terrain.WaterReflectance = 0
Terrain.WaterTransparency = 0
Terrain.WaterWaveSize = 0
Terrain.WaterWaveSpeed = 0
local TriangleMeshPart = {}
local MeshPart = {}
MeshPart.DoubleSided = true
MeshPart.HasJointOffset = true
MeshPart.HasSkinnedMesh = true
local PartOperation = {}
PartOperation.SmoothingAngle = 0
PartOperation.UsePartColor = true
local IntersectOperation = {}
local NegateOperation = {}
local UnionOperation = {}
local TrussPart = {}
local VehicleSeat = {}
VehicleSeat.Disabled = true
VehicleSeat.HeadsUpDisplay = true
VehicleSeat.MaxSpeed = 0
VehicleSeat.SteerFloat = 0
VehicleSeat.ThrottleFloat = 0
VehicleSeat.Torque = 0
VehicleSeat.TurnSpeed = 0
local Model = {}
Model.Scale = 0
local Actor = {}
local BackpackItem = {}
local HopperBin = {}
HopperBin.Active = true
local Tool = {}
Tool.CanBeDropped = true
Tool.Enabled = true
Tool.ManualActivationOnly = true
Tool.RequiresHandle = true
local Flag = {}
local Status = {}
local WorldRoot = {}
local Workspace = {}
Workspace.AirDensity = 0
Workspace.AllowThirdPartySales = true
Workspace.FallenPartsDestroyHeight = 0
Workspace.FilteringEnabled = true
Workspace.Gravity = 0
Workspace.StreamingEnabled = true
Workspace.TouchesUseCollisionGroups = true
local WorldModel = {}
local PackageLink = {}
PackageLink.AutoUpdate = true
local PackageService = {}
local PackageUIService = {}
local Pages = {}
Pages.IsFinished = true
local AudioPages = {}
local CatalogPages = {}
local DataStoreKeyPages = {}
local DataStoreListingPages = {}
local DataStorePages = {}
local DataStoreVersionPages = {}
local FriendPages = {}
local InventoryPages = {}
local EmotesPages = {}
local MemoryStoreHashMapPages = {}
local OutfitPages = {}
local StandardPages = {}
local PartOperationAsset = {}
local ParticleEmitter = {}
ParticleEmitter.Brightness = 0
ParticleEmitter.Drag = 0
ParticleEmitter.Enabled = true
ParticleEmitter.FlipbookStartRandom = true
ParticleEmitter.LightEmission = 0
ParticleEmitter.LightInfluence = 0
ParticleEmitter.LockedToPart = true
ParticleEmitter.Rate = 0
ParticleEmitter.ShapePartial = 0
ParticleEmitter.TimeScale = 0
ParticleEmitter.VelocityInheritance = 0
ParticleEmitter.VelocitySpread = 0
ParticleEmitter.WindAffectsDrag = true
ParticleEmitter.ZOffset = 0
local PatchBundlerFileWatch = {}
local PatchMapping = {}
PatchMapping.FlattenTree = true
local Path = {}
local PathfindingLink = {}
PathfindingLink.IsBidirectional = true
local PathfindingModifier = {}
PathfindingModifier.PassThrough = true
local PathfindingService = {}
PathfindingService.EmptyCutoff = 0
local PausedState = {}
PausedState.AllThreadsPaused = true
local PausedStateBreakpoint = {}
local PausedStateException = {}
local PermissionsService = {}
local PhysicsService = {}
local PhysicsSettings = {}
PhysicsSettings.AllowSleep = true
PhysicsSettings.AreAnchorsShown = true
PhysicsSettings.AreAssembliesShown = true
PhysicsSettings.AreAssemblyCentersOfMassShown = true
PhysicsSettings.AreAwakePartsHighlighted = true
PhysicsSettings.AreBodyTypesShown = true
PhysicsSettings.AreCollisionCostsShown = true
PhysicsSettings.AreConstraintForcesShownForSelectedOrHoveredInstances = true
PhysicsSettings.AreConstraintTorquesShownForSelectedOrHoveredInstances = true
PhysicsSettings.AreContactForcesShownForSelectedOrHoveredAssemblies = true
PhysicsSettings.AreContactIslandsShown = true
PhysicsSettings.AreContactPointsShown = true
PhysicsSettings.AreGravityForcesShownForSelectedOrHoveredAssemblies = true
PhysicsSettings.AreJointCoordinatesShown = true
PhysicsSettings.AreMagnitudesShownForDrawnForcesAndTorques = true
PhysicsSettings.AreMechanismsShown = true
PhysicsSettings.AreModelCoordsShown = true
PhysicsSettings.AreNonAnchorsShown = true
PhysicsSettings.AreOwnersShown = true
PhysicsSettings.ArePartCoordsShown = true
PhysicsSettings.AreRegionsShown = true
PhysicsSettings.AreSolverIslandsShown = true
PhysicsSettings.AreTerrainReplicationRegionsShown = true
PhysicsSettings.AreTimestepsShown = true
PhysicsSettings.AreUnalignedPartsShown = true
PhysicsSettings.AreWorldCoordsShown = true
PhysicsSettings.DisableCSGv2 = true
PhysicsSettings.DisableCSGv3ForPlugins = true
PhysicsSettings.DrawConstraintsNetForce = true
PhysicsSettings.DrawContactsNetForce = true
PhysicsSettings.DrawTotalNetForce = true
PhysicsSettings.EnableForceVisualizationSmoothing = true
PhysicsSettings.FluidForceDrawScale = 0
PhysicsSettings.ForceCSGv2 = true
PhysicsSettings.ForceDrawScale = 0
PhysicsSettings.IsInterpolationThrottleShown = true
PhysicsSettings.IsReceiveAgeShown = true
PhysicsSettings.IsTreeShown = true
PhysicsSettings.ShowDecompositionGeometry = true
PhysicsSettings.ShowFluidForcesForSelectedOrHoveredMechanisms = true
PhysicsSettings.ShowInstanceNamesForDrawnForcesAndTorques = true
PhysicsSettings.TorqueDrawScale = 0
PhysicsSettings.UseCSGv2 = true
local PlaceStatsService = {}
local PlacesService = {}
local PlatformCloudStorageService = {}
local PlatformFriendsService = {}
local Player = {}
Player.AppearanceDidLoad = true
Player.AutoJumpEnabled = true
Player.CameraMaxZoomDistance = 0
Player.CameraMinZoomDistance = 0
Player.CanLoadCharacterAppearance = true
Player.DataReady = true
Player.DevEnableMouseLock = true
Player.GameplayPaused = true
Player.Guest = true
Player.HasVerifiedBadge = true
Player.HealthDisplayDistance = 0
Player.MaximumSimulationRadius = 0
Player.NameDisplayDistance = 0
Player.Neutral = true
Player.SimulationRadius = 0
Player.Teleported = true
Player.TeleportedIn = true
Player.UnfilteredChat = true
Player.VREnabled = true
local PlayerEmulatorService = {}
PlayerEmulatorService.CustomPoliciesEnabled = true
PlayerEmulatorService.PlayerEmulationEnabled = true
PlayerEmulatorService.PseudolocalizationEnabled = true
local PlayerScripts = {}
local PlayerViewService = {}
local Players = {}
Players.BubbleChat = true
Players.CharacterAutoLoads = true
Players.ClassicChat = true
Players.RespawnTime = 0
Players.UseStrafingAnimations = true
local Plugin = {}
Plugin.CollisionEnabled = true
Plugin.GridSize = 0
Plugin.HostDataModelTypeIsCurrent = true
Plugin.UsesAssetInsertionDrag = true
local PluginAction = {}
PluginAction.AllowBinding = true
PluginAction.Checked = true
PluginAction.Enabled = true
local PluginCapabilities = {}
local PluginDebugService = {}
local PluginDragEvent = {}
local PluginGuiService = {}
local PluginManagementService = {}
local PluginManager = {}
local PluginManagerInterface = {}
local PluginMenu = {}
local PluginPolicyService = {}
local PluginToolbar = {}
local PluginToolbarButton = {}
PluginToolbarButton.ClickableWhenViewportHidden = true
PluginToolbarButton.Enabled = true
local PointsService = {}
local PolicyService = {}
local PoseBase = {}
PoseBase.Weight = 0
local NumberPose = {}
local Pose = {}
Pose.MaskWeight = 0
local PostEffect = {}
PostEffect.Enabled = true
local BloomEffect = {}
BloomEffect.Intensity = 0
BloomEffect.Size = 0
BloomEffect.Threshold = 0
local BlurEffect = {}
BlurEffect.Size = 0
local ColorCorrectionEffect = {}
ColorCorrectionEffect.Brightness = 0
ColorCorrectionEffect.Contrast = 0
ColorCorrectionEffect.Saturation = 0
local DepthOfFieldEffect = {}
DepthOfFieldEffect.FarIntensity = 0
DepthOfFieldEffect.FocusDistance = 0
DepthOfFieldEffect.InFocusRadius = 0
DepthOfFieldEffect.NearIntensity = 0
local SunRaysEffect = {}
SunRaysEffect.Intensity = 0
SunRaysEffect.Spread = 0
local ProcessInstancePhysicsService = {}
local ProjectFolderService = {}
local ProximityPrompt = {}
ProximityPrompt.AutoLocalize = true
ProximityPrompt.ClickablePrompt = true
ProximityPrompt.Enabled = true
ProximityPrompt.HoldDuration = 0
ProximityPrompt.MaxActivationDistance = 0
ProximityPrompt.RequiresLineOfSight = true
local ProximityPromptService = {}
ProximityPromptService.Enabled = true
local PublishService = {}
local RbxAnalyticsService = {}
local ReflectionMetadata = {}
local ReflectionMetadataCallbacks = {}
local ReflectionMetadataClasses = {}
local ReflectionMetadataEnums = {}
local ReflectionMetadataEvents = {}
local ReflectionMetadataFunctions = {}
local ReflectionMetadataItem = {}
ReflectionMetadataItem.Browsable = true
ReflectionMetadataItem.ClientOnly = true
ReflectionMetadataItem.Deprecated = true
ReflectionMetadataItem.EditingDisabled = true
ReflectionMetadataItem.IsBackend = true
ReflectionMetadataItem.ServerOnly = true
local ReflectionMetadataClass = {}
ReflectionMetadataClass.Insertable = true
local ReflectionMetadataEnum = {}
local ReflectionMetadataEnumItem = {}
local ReflectionMetadataMember = {}
local ReflectionMetadataProperties = {}
local ReflectionMetadataYieldFunctions = {}
local ReflectionService = {}
local RemoteCursorService = {}
local RemoteDebuggerServer = {}
local RemoteFunction = {}
local RenderSettings = {}
RenderSettings.EagerBulkExecution = true
RenderSettings.Enable VR Mode = true
RenderSettings.EnableFRM = true
RenderSettings.ExportMergeByMaterial = true
RenderSettings.ReloadAssets = true
RenderSettings.RenderCSGTrianglesDebug = true
RenderSettings.ShowBoundingBoxes = true
local RenderingTest = {}
RenderingTest.ComparisonPsnrThreshold = 0
RenderingTest.FieldOfView = 0
RenderingTest.PerfTest = true
RenderingTest.QualityAuto = true
RenderingTest.ShouldSkip = true
local ReplicatedFirst = {}
local ReplicatedStorage = {}
local RibbonNotificationService = {}
local RobloxPluginGuiService = {}
local RobloxReplicatedStorage = {}
local RobloxServerStorage = {}
local RomarkService = {}
local RotationCurve = {}
local RtMessagingService = {}
local RunService = {}
local RuntimeScriptService = {}
local SafetyService = {}
SafetyService.IsCaptureModeForReport = true
local ScreenshotHud = {}
ScreenshotHud.CloseWhenScreenshotTaken = true
ScreenshotHud.ExperienceNameOverlayEnabled = true
ScreenshotHud.HideCoreGuiForCaptures = true
ScreenshotHud.HidePlayerGuiForCaptures = true
ScreenshotHud.UsernameOverlayEnabled = true
ScreenshotHud.Visible = true
local ScriptBuilder = {}
local SyncScriptBuilder = {}
SyncScriptBuilder.CoverageInfo = true
SyncScriptBuilder.DebugInfo = true
SyncScriptBuilder.PackAsSource = true
SyncScriptBuilder.RawBytecode = true
local ScriptChangeService = {}
local ScriptCloneWatcher = {}
local ScriptCloneWatcherHelper = {}
local ScriptCommitService = {}
local ScriptContext = {}
ScriptContext.ScriptsDisabled = true
local ScriptDebugger = {}
ScriptDebugger.IsDebugging = true
ScriptDebugger.IsPaused = true
local ScriptDocument = {}
local ScriptEditorService = {}
local ScriptProfilerService = {}
local ScriptRegistrationService = {}
local ScriptRuntime = {}
local ScriptService = {}
local Selection = {}
Selection.SelectionBoxThickness = 0
Selection.SelectionThickness = 0
Selection.ShowActiveInstanceHighlight = true
local SelectionHighlightManager = {}
local SensorBase = {}
local BuoyancySensor = {}
BuoyancySensor.FullySubmerged = true
BuoyancySensor.TouchingSurface = true
local ControllerSensor = {}
local ControllerPartSensor = {}
ControllerPartSensor.SearchDistance = 0
local ServerScriptService = {}
ServerScriptService.LoadStringEnabled = true
local ServerStorage = {}
local ServiceProvider = {}
local DataModel = {}
DataModel.IsSFFlagsLoaded = true
local GenericSettings = {}
local AnalysticsSettings = {}
local GlobalSettings = {}
local UserSettings = {}
local ServiceVisibilityService = {}
local SessionService = {}
local SharedTableRegistry = {}
local ShorelineUpgraderService = {}
local Sky = {}
Sky.CelestialBodiesShown = true
Sky.MoonAngularSize = 0
Sky.SunAngularSize = 0
local Smoke = {}
Smoke.Enabled = true
Smoke.Opacity = 0
Smoke.RiseVelocity = 0
Smoke.Size = 0
Smoke.TimeScale = 0
local SmoothVoxelsUpgraderService = {}
local SnippetService = {}
local SocialService = {}
local Sound = {}
Sound.EmitterSize = 0
Sound.IsLoaded = true
Sound.IsPaused = true
Sound.IsPlaying = true
Sound.IsSpatial = true
Sound.Looped = true
Sound.MaxDistance = 0
Sound.MinDistance = 0
Sound.Pitch = 0
Sound.PlayOnRemove = true
Sound.PlaybackRegionsEnabled = true
Sound.PlaybackSpeed = 0
Sound.Playing = true
Sound.RollOffGain = 0
Sound.RollOffMaxDistance = 0
Sound.RollOffMinDistance = 0
Sound.Volume = 0
Sound.isPlaying = true
local SoundEffect = {}
SoundEffect.Enabled = true
local ChorusSoundEffect = {}
ChorusSoundEffect.Depth = 0
ChorusSoundEffect.Mix = 0
ChorusSoundEffect.Rate = 0
local CompressorSoundEffect = {}
CompressorSoundEffect.Attack = 0
CompressorSoundEffect.GainMakeup = 0
CompressorSoundEffect.Ratio = 0
CompressorSoundEffect.Release = 0
CompressorSoundEffect.Threshold = 0
local CustomSoundEffect = {}
local AssetSoundEffect = {}
local ChannelSelectorSoundEffect = {}
local DistortionSoundEffect = {}
DistortionSoundEffect.Level = 0
local EchoSoundEffect = {}
EchoSoundEffect.Delay = 0
EchoSoundEffect.DryLevel = 0
EchoSoundEffect.Feedback = 0
EchoSoundEffect.WetLevel = 0
local EqualizerSoundEffect = {}
EqualizerSoundEffect.HighGain = 0
EqualizerSoundEffect.LowGain = 0
EqualizerSoundEffect.MidGain = 0
local FlangeSoundEffect = {}
FlangeSoundEffect.Depth = 0
FlangeSoundEffect.Mix = 0
FlangeSoundEffect.Rate = 0
local PitchShiftSoundEffect = {}
PitchShiftSoundEffect.Octave = 0
local ReverbSoundEffect = {}
ReverbSoundEffect.DecayTime = 0
ReverbSoundEffect.Density = 0
ReverbSoundEffect.Diffusion = 0
ReverbSoundEffect.DryLevel = 0
ReverbSoundEffect.WetLevel = 0
local TremoloSoundEffect = {}
TremoloSoundEffect.Depth = 0
TremoloSoundEffect.Duty = 0
TremoloSoundEffect.Frequency = 0
local SoundGroup = {}
SoundGroup.Volume = 0
local SoundService = {}
SoundService.DistanceFactor = 0
SoundService.DopplerScale = 0
SoundService.RespectFilteringEnabled = true
SoundService.RolloffScale = 0
local Sparkles = {}
Sparkles.Enabled = true
Sparkles.TimeScale = 0
local SpawnerService = {}
local StackFrame = {}
StackFrame.Populated = true
local StandalonePluginScripts = {}
local StarterGear = {}
local StarterPack = {}
local StarterPlayer = {}
StarterPlayer.AllowCustomAnimations = true
StarterPlayer.AutoJumpEnabled = true
StarterPlayer.CameraMaxZoomDistance = 0
StarterPlayer.CameraMinZoomDistance = 0
StarterPlayer.CharacterJumpHeight = 0
StarterPlayer.CharacterJumpPower = 0
StarterPlayer.CharacterMaxSlopeAngle = 0
StarterPlayer.CharacterUseJumpPower = true
StarterPlayer.CharacterWalkSpeed = 0
StarterPlayer.EnableMouseLockOption = true
StarterPlayer.HealthDisplayDistance = 0
StarterPlayer.LoadCharacterAppearance = true
StarterPlayer.NameDisplayDistance = 0
StarterPlayer.UserEmotesEnabled = true
local StarterPlayerScripts = {}
local StarterCharacterScripts = {}
local StartupMessageService = {}
local Stats = {}
Stats.DataReceiveKbps = 0
Stats.DataSendKbps = 0
Stats.HeartbeatTimeMs = 0
Stats.PhysicsReceiveKbps = 0
Stats.PhysicsSendKbps = 0
Stats.PhysicsStepTimeMs = 0
local StatsItem = {}
local RunningAverageItemDouble = {}
local RunningAverageItemInt = {}
local RunningAverageTimeIntervalItem = {}
local TotalCountTimeIntervalItem = {}
local StopWatchReporter = {}
local StreamingService = {}
local Studio = {}
Studio.Always Save Script Changes = true
Studio.Animate Hover Over = true
Studio.Auto Clean Empty Line = true
Studio.Auto Closing Brackets = true
Studio.Auto Closing Quotes = true
Studio.Auto Delete Closing Brackets and Quotes = true
Studio.Auto-Recovery Enabled = true
Studio.Automatically trigger AI Code Completion = true
Studio.Camera Mouse Wheel Speed = 0
Studio.Camera Pan Speed = 0
Studio.Camera Shift Speed = 0
Studio.Camera Speed = 0
Studio.Camera Zoom to Mouse Position = true
Studio.CameraAdaptiveSpeed = true
Studio.CameraTweenFocus = true
Studio.Clear Output On Start = true
Studio.CommandBarLocalState = true
Studio.DeprecatedObjectsShown = true
Studio.DraggerShowHoverRuler = true
Studio.DraggerShowMeasurement = true
Studio.DraggerShowTargetSnap = true
Studio.DraggerSoftSnapMarginFactor = 0
Studio.DraggerSummonMarginFactor = 0
Studio.DraggerTiltRotateDuration = 0
Studio.Enable Autocomplete = true
Studio.Enable Autocomplete Doc View = true
Studio.Enable CoreScript Debugger = true
Studio.Enable Http Sandboxing = true
Studio.Enable Internal Beta Features = true
Studio.Enable Internal Features = true
Studio.Enable Script Analysis = true
Studio.Enable Scrollbar Markers = true
Studio.Enable Signature Help = true
Studio.Enable Signature Help Doc View = true
Studio.Enable Temporary Tabs = true
Studio.Enable Temporary Tabs In Explorer = true
Studio.Enable Type Hover = true
Studio.EnableCodeAssist = true
Studio.EnableIndentationRulers = true
Studio.EnableOnTypeAutocomplete = true
Studio.Format On Paste = true
Studio.Format On Type = true
Studio.FreeCameraSpeedScroll = true
Studio.Highlight Current Line = true
Studio.Highlight Occurances = true
Studio.Hover Box Thickness = 0
Studio.Indent Using Spaces = true
Studio.Line Thickness = 0
Studio.LoadAllBuiltinPluginsInRunModes = true
Studio.LoadUserPluginsInRunModes = true
Studio.LuaDebuggerEnabled = true
Studio.LuaDebuggerEnabledAtStartup = true
Studio.Main Volume = 0
Studio.Only Play Audio from Window in Focus = true
Studio.Physical Draggers Select Scope By Default = true
Studio.PluginDebuggingEnabled = true
Studio.ReloadBuiltinPluginsOnChange = true
Studio.ReloadLocalPluginsOnChange = true
Studio.Respect Studio shortcuts when game has focus = true
Studio.ScriptEditorShouldShowPluginMethods = true
Studio.Scroll Past Last Line = true
Studio.Selection Box Thickness = 0
Studio.Set Pivot of Imported Parts = true
Studio.Show Core GUI in Explorer while Playing = true
Studio.Show Diagnostics Bar = true
Studio.Show FileSyncService = true
Studio.Show Hidden Objects in Explorer = true
Studio.Show Hover Over = true
Studio.Show Light Guides = true
Studio.Show Navigation Labels = true
Studio.Show Navigation Mesh = true
Studio.Show Pathfinding Links = true
Studio.Show Plugin GUI Service in Explorer = true
Studio.Show Singly Selected Attachment Parent Frame = true
Studio.Show Whitespace = true
Studio.Show plus button on hover in Explorer = true
Studio.ShowCorePackagesInExplorer = true
Studio.Skip Closing Brackets and Quotes = true
Studio.Text Wrapping = true
Studio.Use Bounding Box Move Handles = true
local StudioAssetService = {}
local StudioAttachment = {}
StudioAttachment.AutoHideParent = true
StudioAttachment.IsArrowVisible = true
local StudioCallout = {}
StudioCallout.IsArrowVisible = true
StudioCallout.IsNextVisible = true
local StudioData = {}
StudioData.EnableScriptCollabByDefaultOnLoad = true
local StudioDeviceEmulatorService = {}
StudioDeviceEmulatorService.HasMultiTouchStarted = true
StudioDeviceEmulatorService.IsMultiTouchEmulationOn = true
StudioDeviceEmulatorService.IsMultiTouchEnabled = true
local StudioObjectBase = {}
local StudioWidget = {}
local StudioPublishService = {}
StudioPublishService.PublishLocked = true
local StudioScriptDebugEventListener = {}
local StudioSdkService = {}
local StudioService = {}
StudioService.AlignDraggedObjects = true
StudioService.DraggerSolveConstraints = true
StudioService.DrawConstraintsOnTop = true
StudioService.GridSize = 0
StudioService.PivotSnapToGeometry = true
StudioService.RotateIncrement = 0
StudioService.ShowConstraintDetails = true
StudioService.UseLocalSpace = true
local StudioTheme = {}
local StudioWidgetsService = {}
local StyleBase = {}
local StyleRule = {}
local StyleSheet = {}
local StyleDerive = {}
local StyleLink = {}
local StylingService = {}
local SurfaceAppearance = {}
local TaskScheduler = {}
local Team = {}
Team.AutoAssignable = true
Team.AutoColorCharacters = true
local TeamCreateData = {}
local TeamCreatePublishService = {}
local TeamCreateService = {}
local Teams = {}
local TeleportAsyncResult = {}
local TeleportOptions = {}
TeleportOptions.ShouldReserveServer = true
local TeleportService = {}
TeleportService.CustomizedTeleportUI = true
local TemporaryCageMeshProvider = {}
local TemporaryScriptService = {}
local TerrainDetail = {}
TerrainDetail.StudsPerTile = 0
local TerrainRegion = {}
TerrainRegion.IsSmooth = true
local TestService = {}
TestService.AutoRuns = true
TestService.ExecuteWithStudioRun = true
TestService.Is30FpsThrottleEnabled = true
TestService.IsPhysicsEnvironmentalThrottled = true
TestService.IsSleepAllowed = true
local TextBoxService = {}
local TextChannel = {}
local TextChatCommand = {}
TextChatCommand.AutocompleteVisible = true
TextChatCommand.Enabled = true
local TextChatConfigurations = {}
local BubbleChatConfiguration = {}
BubbleChatConfiguration.BubbleDuration = 0
BubbleChatConfiguration.BubblesSpacing = 0
BubbleChatConfiguration.Enabled = true
BubbleChatConfiguration.MaxBubbles = 0
BubbleChatConfiguration.MaxDistance = 0
BubbleChatConfiguration.MinimizeDistance = 0
BubbleChatConfiguration.TailVisible = true
BubbleChatConfiguration.VerticalStudsOffset = 0
local ChatInputBarConfiguration = {}
ChatInputBarConfiguration.AutocompleteEnabled = true
ChatInputBarConfiguration.Enabled = true
ChatInputBarConfiguration.IsFocused = true
ChatInputBarConfiguration.IsFocusedWrite = true
local ChatWindowConfiguration = {}
ChatWindowConfiguration.Enabled = true
ChatWindowConfiguration.HeightScale = 0
ChatWindowConfiguration.WidthScale = 0
local TextChatMessage = {}
local TextChatMessageProperties = {}
local TextChatService = {}
TextChatService.ChatTranslationEnabled = true
TextChatService.ChatTranslationFTUXShown = true
TextChatService.ChatTranslationToggleEnabled = true
TextChatService.CreateDefaultCommands = true
TextChatService.CreateDefaultTextChannels = true
local TextFilterResult = {}
local TextFilterTranslatedResult = {}
local TextService = {}
local TextSource = {}
TextSource.CanSend = true
local TextureGenerationPartGroup = {}
local TextureGenerationService = {}
local TextureGenerationUnwrappingRequest = {}
local ThirdPartyUserService = {}
local ThreadState = {}
ThreadState.Populated = true
local TimerService = {}
local ToastNotificationService = {}
local TouchInputService = {}
local TouchTransmitter = {}
local TracerService = {}
local TrackerLodController = {}
local TrackerStreamAnimation = {}
local Trail = {}
Trail.Brightness = 0
Trail.Enabled = true
Trail.FaceCamera = true
Trail.Lifetime = 0
Trail.LightEmission = 0
Trail.LightInfluence = 0
Trail.MaxLength = 0
Trail.MinLength = 0
Trail.TextureLength = 0
local Translator = {}
local TutorialService = {}
local TweenBase = {}
local Tween = {}
local TweenService = {}
local UGCAvatarService = {}
local UGCValidationService = {}
local UIBase = {}
local UIComponent = {}
local UIConstraint = {}
local UIAspectRatioConstraint = {}
UIAspectRatioConstraint.AspectRatio = 0
local UISizeConstraint = {}
local UITextSizeConstraint = {}
local UICorner = {}
local UIFlexItem = {}
UIFlexItem.GrowRatio = 0
UIFlexItem.ShrinkRatio = 0
local UIGradient = {}
UIGradient.Enabled = true
UIGradient.Rotation = 0
local UILayout = {}
local UIGridStyleLayout = {}
local UIGridLayout = {}
local UIListLayout = {}
UIListLayout.Wraps = true
local UIPageLayout = {}
UIPageLayout.Animated = true
UIPageLayout.Circular = true
UIPageLayout.GamepadInputEnabled = true
UIPageLayout.ScrollWheelInputEnabled = true
UIPageLayout.TouchInputEnabled = true
UIPageLayout.TweenTime = 0
local UITableLayout = {}
UITableLayout.FillEmptySpaceColumns = true
UITableLayout.FillEmptySpaceRows = true
local UIPadding = {}
local UIScale = {}
UIScale.Scale = 0
local UIStroke = {}
UIStroke.Enabled = true
UIStroke.Thickness = 0
UIStroke.Transparency = 0
local UnvalidatedAssetService = {}
local UserGameSettings = {}
UserGameSettings.AllTutorialsDisabled = true
UserGameSettings.CameraYInverted = true
UserGameSettings.ChatTranslationEnabled = true
UserGameSettings.ChatTranslationFTUXShown = true
UserGameSettings.ChatTranslationToggleEnabled = true
UserGameSettings.ChatVisible = true
UserGameSettings.Fullscreen = true
UserGameSettings.GamepadCameraSensitivity = 0
UserGameSettings.HasEverUsedVR = true
UserGameSettings.IsUsingCameraYInverted = true
UserGameSettings.IsUsingGamepadCameraSensitivity = true
UserGameSettings.MasterVolume = 0
UserGameSettings.MasterVolumeStudio = 0
UserGameSettings.MicroProfilerWebServerEnabled = true
UserGameSettings.MouseSensitivity = 0
UserGameSettings.OnScreenProfilerEnabled = true
UserGameSettings.PerformanceStatsVisible = true
UserGameSettings.PlayerHeight = 0
UserGameSettings.PreferredTransparency = 0
UserGameSettings.ReducedMotion = true
UserGameSettings.StartMaximized = true
UserGameSettings.UiNavigationKeyBindEnabled = true
UserGameSettings.UsedCoreGuiIsVisibleToggle = true
UserGameSettings.UsedCustomGuiIsVisibleToggle = true
UserGameSettings.UsedHideHudShortcut = true
UserGameSettings.VREnabled = true
UserGameSettings.VRSmoothRotationEnabled = true
UserGameSettings.VRSmoothRotationEnabledCustomOption = true
UserGameSettings.VRThirdPersonFollowCamEnabled = true
UserGameSettings.VRThirdPersonFollowCamEnabledCustomOption = true
UserGameSettings.VignetteEnabled = true
UserGameSettings.VignetteEnabledCustomOption = true
local UserInputService = {}
UserInputService.AccelerometerEnabled = true
UserInputService.GamepadEnabled = true
UserInputService.GyroscopeEnabled = true
UserInputService.KeyboardEnabled = true
UserInputService.LegacyInputEventsEnabled = true
UserInputService.ModalEnabled = true
UserInputService.MouseDeltaSensitivity = 0
UserInputService.MouseEnabled = true
UserInputService.MouseIconEnabled = true
UserInputService.OnScreenKeyboardVisible = true
UserInputService.TouchEnabled = true
UserInputService.VREnabled = true
local UserService = {}
local VRService = {}
VRService.AvatarGestures = true
VRService.DidPointerHit = true
VRService.FadeOutViewOnCollision = true
VRService.LaserDistance = 0
VRService.QuestASWState = true
VRService.QuestDisplayRefreshRate = 0
VRService.ThirdPersonFollowCamEnabled = true
VRService.VRDeviceAvailable = true
VRService.VREnabled = true
local VRStatusService = {}
local ValueBase = {}
local BinaryStringValue = {}
local BoolValue = {}
BoolValue.Value = true
local BrickColorValue = {}
local CFrameValue = {}
local Color3Value = {}
local DoubleConstrainedValue = {}
local IntConstrainedValue = {}
local IntValue = {}
local NumberValue = {}
local ObjectValue = {}
local RayValue = {}
local StringValue = {}
local Vector3Value = {}
local Vector3Curve = {}
local VersionControlService = {}
VersionControlService.ScriptCollabEnabled = true
local VideoCaptureService = {}
VideoCaptureService.Active = true
local VideoDeviceInput = {}
VideoDeviceInput.Active = true
VideoDeviceInput.IsReady = true
local VideoService = {}
local VirtualInputManager = {}
local VirtualUser = {}
local VisibilityCheckDispatcher = {}
local Visit = {}
local VisualizationMode = {}
VisualizationMode.Enabled = true
local VisualizationModeCategory = {}
VisualizationModeCategory.Enabled = true
local VisualizationModeService = {}
local VoiceChatInternal = {}
local VoiceChatService = {}
VoiceChatService.EnableDefaultVoice = true
VoiceChatService.UseNewAudioApi = true
VoiceChatService.UseNewControlPaths = true
VoiceChatService.UseNewJoinFlow = true
VoiceChatService.UseRME = true
VoiceChatService.VoiceChatEnabledForPlaceOnRcc = true
VoiceChatService.VoiceChatEnabledForUniverseOnRcc = true
local WeldConstraint = {}
WeldConstraint.Active = true
WeldConstraint.Enabled = true
local Wire = {}
Wire.Connected = true